"""
Test SimulationInputBuilder with real test data files
Tests that the builder correctly loads and processes various input file formats
"""
import pytest
import json
import os
from pathlib import Path
import subprocess
import shutil
import tempfile
import glob

# Paths
GCMC_CPU_PATH = Path(__file__).parent.parent.parent / "build" / "bin" / "gcmc_cpu"
TEST_DATA_DIR = Path(__file__).parent.parent / "data"
CHARMM_FF_DIR = TEST_DATA_DIR / "charmm36.ff"


def cleanup_generated_files(directory):
    """Clean up ONLY specific files generated by gcmc_cpu - NOT using wildcards"""
    # List specific filenames to delete - NO WILDCARDS
    specific_files = [
        "gcmc_final.txt",
        "gcmc_final.pdb",
        "gcmc_final.checkpoint",
        "gcmc_final.top"
    ]
    
    if isinstance(directory, str):
        directory = Path(directory)
    
    # Only delete these specific files
    for filename in specific_files:
        file_path = directory / filename
        if file_path.exists():
            try:
                file_path.unlink()
            except:
                pass  # Ignore errors
    
    # Also look for numbered output files with specific patterns
    # Only delete files that match the exact pattern of GCMC outputs
    for file in directory.iterdir():
        if file.is_file():
            # Only delete files matching exact GCMC output patterns
            name = file.name
            if (name.startswith("test.") and ".gc." in name and 
                (name.endswith(".pdb") or name.endswith(".top"))):
                try:
                    file.unlink()
                except:
                    pass


class TestSimulationInputBuilder:
    """Test SimulationInputBuilder with real test data"""
    
    @pytest.fixture(autouse=True)
    def cleanup(self, tmp_path):
        """Automatic cleanup after each test"""
        yield
        # Only clean up in temp directories, never in source directories
        # The tests should run in tmp_path anyway
    
    @pytest.fixture
    def test_paths(self):
        """Provide paths to real test data files"""
        return {
            'pdb_sol': CHARMM_FF_DIR / "mol" / "sol.pdb",
            'pdb_benx': CHARMM_FF_DIR / "mol" / "benx.pdb",
            'pdb_acox': CHARMM_FF_DIR / "mol" / "acox.pdb",
            'itp_sol': CHARMM_FF_DIR / "mol" / "sol.itp",
            'itp_benx': CHARMM_FF_DIR / "mol" / "benx.itp", 
            'itp_acox': CHARMM_FF_DIR / "mol" / "acox.itp",
            'par_ff': CHARMM_FF_DIR / "ffnonbonded.itp",
            'par_nbfix': CHARMM_FF_DIR / "nbfix.itp",
            'inp_quick': TEST_DATA_DIR / "gcmc_quick.inp"
        }
    
    def test_load_complete_input_files(self, test_paths, tmp_path):
        """Test loading complete set of input files (INP + PDB + TOP + PAR)"""
        # Use a temporary directory to avoid polluting the source tree.
        # Assert behavior via --dump-params (no stdout/stderr log-string matching).
        with tempfile.TemporaryDirectory() as temp_dir:
            work = Path(temp_dir)

            # Copy all test data files to work so relative paths resolve.
            for file in ["gcmc_quick.inp", "test.pdb", "test.top"]:
                src = TEST_DATA_DIR / file
                assert src.exists(), f"Missing test data file: {src}"
                shutil.copy(src, work / file)

            assert (TEST_DATA_DIR / "charmm36.ff").exists(), "Missing charmm36.ff test data"
            shutil.copytree(TEST_DATA_DIR / "charmm36.ff", work / "charmm36.ff")

            mol_link = work / "mol"
            if not mol_link.exists():
                mol_link.symlink_to("charmm36.ff/mol")

            temp_inp = work / "gcmc_quick.inp"
            # Keep it fast: this test is about input loading, not production sampling.
            content = temp_inp.read_text()
            content = content.replace("eqsteps:10", "eqsteps:0")
            content = content.replace("mcsteps:100", "mcsteps:0")
            temp_inp.write_text(content)

            out_prefix = work / "out" / "gcmc"
            out_prefix.parent.mkdir(parents=True, exist_ok=True)
            params_json = work / "out" / "params.json"

            result = subprocess.run(
                [
                    str(GCMC_CPU_PATH),
                    "--inp",
                    str(temp_inp),
                    "--seed",
                    "42",
                    "--prefix",
                    str(out_prefix),
                    "--dump-params",
                    str(params_json),
                ],
                cwd=work,
                capture_output=True,
                text=True,
                timeout=20,
            )

            assert result.returncode != -11, "Segfault with complete input files"
            assert result.returncode == 0, result.stdout + result.stderr
            assert params_json.exists(), "params.json not generated"

            params = json.loads(params_json.read_text())
            assert params["basic"]["inp_units"] == "gcmc_gpu"
            names = [str(x).strip() for x in params["fragment"]["names"]]
            assert names and all(names)
            assert len(names) >= 3
            lower_names = {n.lower() for n in names}
            assert {"sol", "benx"}.issubset(lower_names)
            assert [float(x) for x in params["space"]["box_size_nm"]] == pytest.approx(
                [3.6736, 4.0850, 4.9379], abs=1e-4
            )
            assert float(params["mc"]["temperature_K"]) == pytest.approx(300.0, abs=1e-6)
        
    def test_load_pdb_only_no_crash(self, test_paths, tmp_path):
        """Test that PDB-only input doesn't crash"""
        # Create minimal INP referencing only PDB
        inp_file = tmp_path / "pdb_only.inp"
        inp_file.write_text(f"""
pdb:{test_paths['pdb_sol']}
box_size:10.0 10.0 10.0
temperature:298.15
mcsteps:100
fragname:water
fragconc:55.0
fragmuex:-5.0
""")
        
        result = subprocess.run(
            [str(GCMC_CPU_PATH), "--inp", str(inp_file), "--seed", "42"],
            cwd=tmp_path,  # Run in temp directory to avoid polluting source
            capture_output=True,
            text=True,
            timeout=5
        )
        
        # Clean up any generated files
        cleanup_generated_files(tmp_path)
        
        # Should not segfault
        assert result.returncode != -11, "Segfault with PDB-only input"
    
    def test_load_fragment_itp_files(self, test_paths, tmp_path):
        """Test loading fragment ITP files"""
        # Create INP that loads fragment ITPs
        inp_file = tmp_path / "fragments.inp"
        inp_file.write_text(f"""
fragitp:{test_paths['itp_sol']}
fragitp:{test_paths['itp_benx']}
fragitp:{test_paths['itp_acox']}
box_size:10.0 10.0 10.0
cutoff:4.0
temperature:298.15
mcsteps:0
fragname:SOL BENX ACOX
fragconc:55.0 1.0 1.0
fragmuex:-5.0 -0.79 -0.5
moves_per_step:1
""")
        params_json = tmp_path / "params.json"

        result = subprocess.run(
            [str(GCMC_CPU_PATH), "--inp", str(inp_file), "--seed", "42", "--dump-params", str(params_json)],
            cwd=tmp_path,  # Run in temp directory
            capture_output=True,
            text=True,
            timeout=20
        )
        
        # Clean up any generated files
        cleanup_generated_files(tmp_path)
        
        # Should not crash
        assert result.returncode != -11, "Failed to load fragment ITPs"
        
        assert params_json.exists()
        params = json.loads(params_json.read_text())
        names = [str(n).strip().upper() for n in params["fragment"]["names"]]
        assert names == ["SOL", "BENX", "ACOX"]
        assert [float(x) for x in params["fragment"]["conc_list_M"]] == pytest.approx([55.0, 1.0, 1.0], abs=1e-6)
        assert [float(x) for x in params["fragment"]["muex_list_kj_mol"]] == pytest.approx(
            [-5.0 * 4.184, -0.79 * 4.184, -0.5 * 4.184], abs=2e-3
        )
    
    def test_load_parameter_files(self, test_paths, tmp_path):
        """Test loading force field parameter files"""
        inp_file = tmp_path / "params.inp"
        inp_file.write_text(f"""
par:{test_paths['par_ff']}
par:{test_paths['par_nbfix']}
box_size:20.0 20.0 20.0
temperature:300.0
mcsteps:100
fragname:water
fragconc:55.0
fragmuex:-5.0
""")
        
        result = subprocess.run(
            [str(GCMC_CPU_PATH), "--inp", str(inp_file), "--seed", "42"],
            cwd=tmp_path,  # Run in temp directory
            capture_output=True,
            text=True,
            timeout=5
        )
        
        # Clean up any generated files
        cleanup_generated_files(tmp_path)
        
        # Should complete without errors
        assert result.returncode != -11, "Failed to load parameter files"
    
    def test_empty_files_graceful_handling(self, tmp_path):
        """Test that empty input files are handled gracefully"""
        # Create empty PDB and TOP files
        empty_pdb = tmp_path / "empty.pdb"
        empty_pdb.write_text("END\n")
        
        empty_top = tmp_path / "empty.top"
        empty_top.write_text("[ system ]\nEmpty\n[ molecules ]\n")
        
        inp_file = tmp_path / "empty.inp"
        inp_file.write_text(f"""
pdb:{empty_pdb}
top:{empty_top}
box_size:10.0 10.0 10.0
temperature:298.15
mcsteps:100
fragname:water
fragconc:55.0
fragmuex:-5.0
""")
        
        result = subprocess.run(
            [str(GCMC_CPU_PATH), "--inp", str(inp_file), "--seed", "42"],
            cwd=tmp_path,  # Run in temp directory
            capture_output=True,
            text=True,
            timeout=5
        )

        # Should not crash
        assert result.returncode != -11, "Segfault with empty files"

        # Either fail cleanly (non-zero) or succeed while producing an empty final PDB.
        if result.returncode == 0:
            out_pdb = tmp_path / "gcmc_final.pdb"
            assert out_pdb.exists(), "Expected gcmc_final.pdb for successful run"
            atom_lines = [
                line for line in out_pdb.read_text().splitlines()
                if line.startswith(("ATOM", "HETATM"))
            ]
            assert not atom_lines, f"Expected empty output PDB, found {len(atom_lines)} atoms"

        # Clean up any generated files
        cleanup_generated_files(tmp_path)
    
    def test_parameter_preservation(self, tmp_path, test_paths):
        """Test that INP parameters are correctly preserved"""
        inp_file = tmp_path / "params_test.inp"
        # Create a more complete INP file with fragment ITPs
        inp_file.write_text(
            f"""
fragitp:{test_paths['itp_sol']}
inp_units:nm
box_size:3.21 4.32 5.43
temperature:310.0
mcsteps:1000
eqsteps:500
fragname:SOL
fragconc:10.0
fragmuex:-2.5
nprint:50
cutoff:1.2
""".strip()
            + "\n"
        )

        params_json = tmp_path / "params.json"
        result = subprocess.run(
            [
                str(GCMC_CPU_PATH),
                "--inp",
                str(inp_file),
                "--seed",
                "42",
                "--dump-params",
                str(params_json),
            ],
            cwd=tmp_path,  # Run in temp directory
            capture_output=True,
            text=True,
            timeout=5
        )
        
        # Clean up any generated files
        cleanup_generated_files(tmp_path)

        assert result.returncode == 0, result.stdout + result.stderr
        assert params_json.exists()

        params = json.loads(params_json.read_text())
        assert params["basic"]["inp_units"] == "nm"
        assert [float(x) for x in params["space"]["box_size_nm"]] == pytest.approx(
            [3.21, 4.32, 5.43], abs=1e-5
        )
        assert float(params["space"]["cutoff_nm"]) == pytest.approx(1.2, abs=1e-6)
        assert [float(x) for x in params["fragment"]["conc_list_M"]] == pytest.approx(
            [10.0], abs=1e-6
        )
        assert [float(x) for x in params["fragment"]["muex_list_kj_mol"]] == pytest.approx(
            [-2.5], abs=1e-6
        )
    
    def test_mixed_input_sources(self, test_paths, tmp_path):
        """Test mixing different input sources (INP + PDB + ITP)"""
        # Copy a PDB file to temp dir for testing
        test_pdb = tmp_path / "test.pdb" 
        shutil.copy(test_paths['pdb_sol'], test_pdb)
        
        inp_file = tmp_path / "mixed.inp"
        inp_file.write_text(f"""
pdb:{test_pdb}
fragitp:{test_paths['itp_benx']}
par:{test_paths['par_ff']}
box_size:15.0 15.0 15.0
temperature:298.15
mcsteps:10
fragname:BENX
fragconc:1.0
fragmuex:-0.79
moves_per_step:1
""")

        result = subprocess.run(
            [str(GCMC_CPU_PATH), "--inp", str(inp_file), "--seed", "42"],
            cwd=tmp_path,  # Run in temp directory
            capture_output=True,
            text=True,
            timeout=20
        )
        
        # Clean up any generated files
        cleanup_generated_files(tmp_path)
        
        # Should handle mixed inputs without crash
        assert result.returncode != -11, "Failed with mixed input sources"
    
    def test_nonexistent_file_error(self, tmp_path, test_paths):
        """Test that non-existent files are handled with error messages"""
        inp_file = tmp_path / "bad_ref.inp"
        # Add fragment ITP so parser doesn't fail on missing fragment info
        inp_file.write_text(f"""
pdb:/nonexistent/path/file.pdb
top:/another/bad/file.top
fragitp:{test_paths['itp_sol']}
box_size:10.0 10.0 10.0
temperature:298.15
mcsteps:100
fragname:SOL
fragconc:55.0
fragmuex:-5.0
""")
        
        result = subprocess.run(
            [str(GCMC_CPU_PATH), "--inp", str(inp_file)],
            cwd=tmp_path,  # Run in temp directory
            capture_output=True,
            text=True,
            timeout=5
        )

        # Should not crash; should fail cleanly when referenced files are missing.
        assert result.returncode != -11, "Segfault on missing file references"
        assert result.returncode != 0, "Expected failure for missing file references"

        # Clean up any generated files
        cleanup_generated_files(tmp_path)


class TestParameterLogging:
    """Test that simulation parameters are exported in a stable, machine-readable form."""
    
    @pytest.fixture(autouse=True) 
    def cleanup(self, tmp_path):
        """Automatic cleanup after each test"""
        yield
        # Only clean up in temp directories, never in source directories
        # The tests should run in tmp_path anyway
    
    def test_log_output_format(self, tmp_path):
        """Test that --dump-params contains key simulation parameters (no stdout parsing)."""
        with tempfile.TemporaryDirectory() as temp_dir:
            temp_dir = Path(temp_dir)
            
            # Check if test data exists before trying to copy it
            if not (TEST_DATA_DIR / "charmm36.ff").exists():
                pytest.skip("Test data directory not found")
                
            # Use a real test INP file that has all required fields
            test_inp = TEST_DATA_DIR / "gcmc_quick.inp"
            if not test_inp.exists():
                pytest.skip("Test INP file not found")
            
            # Copy all necessary test data to temp directory
            for file in ['test.pdb', 'test.top']:
                src = TEST_DATA_DIR / file
                if src.exists():
                    shutil.copy(src, temp_dir / file)
                    
            # Copy charmm36.ff directory
            shutil.copytree(TEST_DATA_DIR / "charmm36.ff", temp_dir / "charmm36.ff")
            
            # Create mol symlink if needed
            mol_link = temp_dir / "mol"
            if not mol_link.exists():
                mol_link.symlink_to("charmm36.ff/mol")
            
            # Create a simpler version with fewer steps
            inp_content = test_inp.read_text()
            # Replace mcsteps line
            inp_content = inp_content.replace("mcsteps:100", "mcsteps:0")
            inp_content = inp_content.replace("eqsteps:10", "eqsteps:0")
            
            inp_file = temp_dir / "log_test.inp"
            inp_file.write_text(inp_content)
            params_json = temp_dir / "params.json"

            result = subprocess.run(
                [str(GCMC_CPU_PATH), "--inp", str(inp_file), "--seed", "42", "--dump-params", str(params_json)],
                cwd=temp_dir,  # Run in temp_dir where all files are
                capture_output=True,
                text=True,
                timeout=10
            )

            assert result.returncode == 0, result.stdout + result.stderr
            assert params_json.exists()
            params = json.loads(params_json.read_text())
            assert float(params["mc"]["temperature_K"]) == pytest.approx(300.0, abs=1e-6)
            assert len(params["space"]["box_size_nm"]) == 3

            # Clean up any generated files immediately
            cleanup_generated_files(temp_dir)


if __name__ == "__main__":
    pytest.main([__file__, "-v", "-s"])
